In [ ]:
import pandas as pd
import numpy as np
import sklearn as sk

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix, f1_score, classification_report, make_scorer
from sklearn import model_selection

In [ ]:
df = pd.read_csv('finalcsv.csv')
df.head()

FileNotFoundError: ignored

In [ ]:
# define inputs and target
inputs = df[df.columns[1:18]]
target = df['citation']

In [ ]:
# test train split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size = 0.1)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(76136, 17) (8460, 17) (76136,) (8460,)


In [ ]:
## KNN model, k=5
k = 5
neigh = KNeighborsClassifier(n_neighbors = k)
neigh.fit(X_train, y_train)
y_hat = neigh.predict(X_test)

In [ ]:
# model evaluation
score = neigh.score(X_test, y_test)
print('The mean accuracy score on this model is:' , score)
print('Confusion matrix:')
print(confusion_matrix(y_test, y_hat))
target_names = ['Citation given', 'Citation not given']
print('Classification report:')
print(classification_report(y_test, y_hat, target_names=target_names))

The mean accuracy score on this model is: 0.7713947990543735
Confusion matrix:
[[6212  280]
 [1654  314]]
Classification report:
                    precision    recall  f1-score   support

    Citation given       0.79      0.96      0.87      6492
Citation not given       0.53      0.16      0.25      1968

          accuracy                           0.77      8460
         macro avg       0.66      0.56      0.56      8460
      weighted avg       0.73      0.77      0.72      8460



In [ ]:
## Naive bayes model
gnb = GaussianNB()
gnb.fit(X_train, y_train)
y_gnb = gnb.predict(X_test)

In [ ]:
# model evaluation
gnbscore = gnb.score(X_test, y_test)
print('The mean accuracy score on this model is:' , gnbscore)
print('Confusion matrix:')
print(confusion_matrix(y_test, y_gnb))
target_names = ['Citation given', 'Citation not given']
print('Classification report:')
print(classification_report(y_test, y_gnb, target_names=target_names))

The mean accuracy score on this model is: 0.4215130023640662
Confusion matrix:
[[1622 4870]
 [  24 1944]]
Classification report:
                    precision    recall  f1-score   support

    Citation given       0.99      0.25      0.40      6492
Citation not given       0.29      0.99      0.44      1968

          accuracy                           0.42      8460
         macro avg       0.64      0.62      0.42      8460
      weighted avg       0.82      0.42      0.41      8460



In [ ]:
## Logistic regression model
lr = LogisticRegression(solver = 'liblinear')
lr.fit(X_train, y_train)
y_lr = lr.predict(X_test)

In [ ]:
# model evaluation
lrscore = lr.score(X_test, y_test)
print('The mean accuracy score on this model is:', lrscore)
print('Confusion matrix:')
print(confusion_matrix(y_test, y_lr))
target_names = ['Citation given', 'Citation not given']
print('Classification report:')
print(classification_report(y_test, y_lr, target_names=target_names))

The mean accuracy score on this model is: 0.798936170212766
Confusion matrix:
[[6253  239]
 [1462  506]]
Classification report:
                    precision    recall  f1-score   support

    Citation given       0.81      0.96      0.88      6492
Citation not given       0.68      0.26      0.37      1968

          accuracy                           0.80      8460
         macro avg       0.74      0.61      0.63      8460
      weighted avg       0.78      0.80      0.76      8460

